### ISSUE TITLE
[2-3 + 4 h.] 5s controlled zone names from manifest

### ISSUE THREAD

**Issue by mavsejko** [5sControl/5s-backend#405]
В 5с реализовать выбор Controlled zone (выпадающий список), имя зоны в формате 

AssetClass.Asset.Template1
AssetClass.Asset.Template1.Step_name1
AssetClass.Asset.Template1.Step_name2
AssetClass.Asset.Template1.Step_name3
AssetClass.Asset.Template2
AssetClass.Asset.Template2.Step_name1
AssetClass.Asset.Template2.Step_name2
AssetClass.Asset.Template2.Step_name3

update, начинаем с Asset

**Comment by Dimskay1988** [comment]
![Image](https://github.com/user-attachments/assets/1dce1c35-ee6f-42a8-a949-d127740edc9b)



![Image](https://github.com/user-attachments/assets/242a5597-9716-4cfb-a775-bd7ba01cf5d1)

**Comment by Dimskay1988** [comment]
![Image](https://github.com/user-attachments/assets/d3410233-9b93-494e-a9ef-4d6dd785a808)

**Comment by Dimskay1988** [comment]
![Image](https://github.com/user-attachments/assets/453981b0-92d5-4726-9703-e8508f0f85cc)
